# Generated by Django 5.2.2 on 2025-07-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, unique=True)),
                ('local', models.CharField(max_length=256)),
                ('horario_abre', models.TimeField()),
                ('horario_fecha', models.TimeField()),
                ('foto', models.ImageField(upload_to='static/fotos_lugar/')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
